name: Test and Merge
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - work
    paths:
      - "lua/**"
      - "tests/**"
      - ".github/workflows/**"
      - "Makefile"
  workflow_dispatch:

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: "stable"

      - name: Setup StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --version

      - name: Install Plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim /tmp/plenary.nvim

      - name: Run Tests
        env:
          STYLUA_PATH: stylua
          PLENARY_PATH: /tmp/plenary.nvim
        run: make all

  deploy:
    if: github.repository_owner == 'tar80'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Automated Merge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          if ! git merge origin/work --ff-only; then
            echo "Error: Fast-forward merge is not possible."
            exit 1
          fi
          git push origin main
          git push origin --delete work
