name: Quick Merge
on:
  push:
    branches:
      - work
    paths-ignore:
      - 'lua/**'
      - 'tests/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'tar80'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Automated Merge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          if ! git merge origin/work --ff-only; then
            echo "Error: Fast-forward merge is not possible."
            exit 1
          fi
          git push origin main
          git push origin --delete work
